title: Squamish Technology Meetup Group

theme: minima

analytics: true

header_pages:
  - code-of-conduct.md
  - speaking.md
  - sponsors.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
